# test-every-push.yml

# workflow의 이름. 나중에 해당 값을 사용할 수 있기 때문에 저는 유니크하게 사용합니다.
# add dep
name: 'main'

on: push

jobs:
  test:
    # job의 이름을 정해줍니다.
    name: Test lint, tsc, build
    # 저는 해당 job을 리눅스 환경에서 사용할 거예요. 다른 플랫폼이 올 수도 있겠죠?
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        # with라는 키워드로 Action에 값을 전달할 수 있어요.
        # 이 Action은 node-version이라는 값을 받을 수 있네요?
        # 아까 NODE_VERSION이라는 Secret을 만들었는데요,
        # ${{ secrets.XXX }}라는 값으로 GitHub의 Secrets 값을 가져올 수 있어요.
        # node-version은 16.13.1이 되겠죠?
        with:
          node-version: ${{ secrets.NODE_VERSION }}


      - name: Send slack when failed
        # 실패했을 때 실행되겠죠?
        if: ${{ failure() }}
        # 직접 '만든' Action이므로 uses 키워드를 이용해서 아래 경로를 입력해줍니다.
        uses: ./.github/actions/slack-notify
        # 아까 secrets로 접근할 수 있게 만들어놓은 슬랙 url을 여기에 써볼게요.
        # with 키워드와 함께 slack_incoming_url 값으로 넘겨줍니다.
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Send slack if completed
        # 성공할 때만 실행되겠죠?
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        # status input은 받는 쪽에서 default 값을 정해놨기 때문에 success일 때만 넘겨줄게요.
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}